# Generated by Django 6.0.4 on 2026-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_education_resume_experience_resume_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
