# Generated by Django 6.0.4 on 2026-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_github_resume_linkedin_resume_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gfg',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='leetcode',
            field=models.URLField(blank=True),
        ),
    ]
